[build]
command = "npm run build"
publish = "build/client"

# Set immutable caching for static files, because they have fingerprinted filenames

[[headers]]
for = "/assets/*"
[headers.values]
"Cache-Control" = "public, max-age=31560000, immutable"

[[redirects]]
    from = "/*"
    to = "/index.html"
    status = 200
